(add-to-list 'load-path (expand-file-name "~/.emacs.d"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/elisp"))

(require 'iso-transl)
(require 'init-autopair)
;(require 'init-auctex)
(require 'init-auto-complete)
(require 'init-csharp)
(require 'init-misc)
(require 'init-multiple-cursors)
(require 'init-org)
(require 'init-themes)
(require 'init-vala)
(require 'init-evil)
;(require 'init-yasnippet)
(require 'init-smex)
(require 'init-ido-vertical-mode)
(require 'init-ace-jump)

(require 'emacs-settings)
(require 'key-bindings)
